### ISSUE TITLE
Clippy warnings in auto generated code: derive-partial-eq-without-eq

### ISSUE THREAD

**Issue by arvid-norlander** [tokio-rs/prost#1261]
I'm getting many instances of [`clippy::derive-partial-eq-without-eq`](https://rust-lang.github.io/rust-clippy/master/index.html#/derive-partial-eq-without-eq) (an non-default lint that I like to enable for my code) for auto-generated code from prost/prost-build. E.g.

```
warning: you are deriving `PartialEq` and can implement `Eq`
   --> .../target/debug/build/crate_name-8fbbd81e799a35b3/out/analysis.rs:216:17
    |
216 | #[derive(Clone, PartialEq, ::prost::Message)]
    |                 ^^^^^^^^^ help: consider deriving `Eq` as well: `PartialEq, Eq`
```

This happens on for example the following protobuf code (which comes from the bazel project):

```proto
syntax = "proto3";

// ...

// A set of fragment options.
message FragmentOptions {
  // The name of this set of fragment options.
  string name = 1;

  // The options themselves, in sorted order by name.
  repeated Option options = 2;
}

// A fragment option.
message Option {
  // The name of the option.
  optional string name = 1;

  // The value of the option.
  optional string value = 2;
}
```

For some reason Prost marks `Option` as implementing `Eq`, but not `FragmentOptions`. Which triggers clippy. And I think clippy is right in this case.

Note that there is a workaround available:

```rust
mod proto {
    #![allow(clippy::derive_partial_eq_without_eq)]
    #![allow(clippy::doc_lazy_continuation)]
    #![allow(clippy::enum_variant_names)]
    // ...
    include!(concat!(env!("OUT_DIR"), "/includes.rs"));
}
```

Most of those are reasonable to ignore for protobuf generated code, but `derive_partial_eq_without_eq` looks like an actual problem to my eye in the generated code.

**Comment by caspermeijn** [comment]
I did some work to automatically derive `Eq` where possible in https://github.com/tokio-rs/prost/pull/1175

That has not yet been released. Can you verify the clippy warnings are fixed on the main branch of `prost-build`?

**Comment by arvid-norlander** [comment]
I tried that, using commit fcf610ed, but I still get a bunch of these warnings, including the one from the example snippet above.

**Comment by caspermeijn** [comment]
This is a bug. We mark repeated fields as non-eq, because we can't detect nested+repeated field properly. This is a limitation of the current codebase. This should be fixed, but will be a breaking change.

The example in the initial comment is a good reproducer. Thank you for providing that.
